|
  ---
  isLocal: false
  port: 8080
  logLevel: "critical"
  projectId: "p2020-piq-dev"
  logName: "asset-configuration"
  namespaceDB: "asset-configuration"
  gcs_bundle_name: "dev_asset_configuration"
  confFile: "config-dev"
  cacheHost: "redis-master.default.svc.cluster.local:6379"
  cacheDBNumber: 1
  cacheTTL: 60
  enableCache: false
  LoggerSizeLogQueue: 30
  LoggerSizeSendQueue: 10
  LoggerTimeoutQueueHandler: 60
  enableSecurity: false
  certFilePath: "../cert/service.pem"
  keyFilePath: "../cert/service.key"
  authenticationUrl: "https://evd.processiq.cloud.slb-ds.com/api/auth/validateToken"
