|
  ---
  isLocal: false
  logLevel: "info"
  nimbusServer: "https://api.p4d.nimbus.slb-ds.com"
  latestTagsNimbusAPI: "api/api-gateway/v1/all-latest-tags"
  historyTagsNimbusAPI: "api/api-gateway/v1/history-tags"
  projectId: "p2020-piq-dev"
  nimbusGroup: "processiq"
  googleIdentityAPI: "https://www.googleapis.com/auth/userinfo.email"
  assetManagementServer: "http://asset-management:8080"
  assetManagementConfigAPI: "api/assetmanagement/graphql"
  unitManagementServer: "http://piq-unit-management:8080"
  getStreamTemplateLibraryAPI: "api/unitmanagement/streamtemplate-library"
  getUnitSystemAPI: "api/unitmanagement/unit-system"
  getUnitConversionLibraryAPI: "api/unitmanagement/unit-conversion-library"
  timeseriesServer: "http://timeseries:8080"
  timeseriesFacilitySubrouter: "/api/timeseries/facilities"
  writePIQEntityDataAPI: "/%s/piq-entity-records"
  readPIQEntityDataByTimeRangeAPI: "/%s/piq-entities/%s/records"
  logName: "ingestion"
  enableDebugLog: true
  defaultStreamTemplateLibrary: "default"
  defaultUnitSystem: "default"
  defaultUnitConversionLibrary: "default"
  bqCommService: "http://piq-bq-communicator:8080"
  bqCommIngestionAPI: "api/bq-communicator/broadcast"
  mockNimbusBucketName: "piq-dev-mock-nimbus-storage"
  eventDetectionTopic: "EventDetectionTopic"
  ppsConsumptionAPI: "https://api.evq.csp.slb.com/pps-piq/service/timeseries/v1/ts/batch"
  piqServiceId: "pps-ingestion-service-processiq.slbservice.com"
  tokenSvcUrl: "https://p4d.csi.cloud.slb-ds.com/v2"
  ppsMappingBucketName: "dev-piq-pps-mapping"
  sqlInstanceId: "p2020-processiq-mysql"
  sqlDBInstanceName: "processiqDB"
  sqlDBConnectionName: "p2020-piq-dev:us-central1:p2020-processiq-mysql"
  sqlInsertBatchSize: 2048
  sqlDataSize: 90
  pss-datapartition-id: "slb"
  defaultGriddingFreq: 60
  labMeasurementDSKind: "SampleDataPoint"
  communicateWithBQ: true
  statusTagBucket: "dev-piq-status-tags"
